# Generated by Django 3.2.9 on 2021-11-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
